name: Build

on:
  push:
  pull_request:
  release:
    types:
      - published
  schedule:
    # At 12:00 on every day-of-month
    - cron: "0 12 */1 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_dist:
    name: Source and wheel distributions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build distributions
        run: pipx run build[virtualenv] --sdist --wheel

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*

  upload_pypi:
    needs: [build_dist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.8.10
        with:
          password: ${{ secrets.PYPI_PASSWORD }}
