name: Run

on:
  push:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: test ${{ matrix.tox_env }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - {"py": "3.10", "tox_env": "py310-cov"}
          - {"py": "3.10", "tox_env": "py310"}
          - {"py": "3.9", "tox_env": "py39"}
          - {"py": "3.8", "tox_env": "py38"}
    steps:
      - name: setup python for tox
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: install tox
        run: python -m pip install tox
      - uses: actions/checkout@v3
      - name: setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.py }}
      - name: setup test suite ${{ matrix.tox_env }}
        run: tox -vv --notest -e ${{ matrix.tox_env }}
      - name: run test suite ${{ matrix.tox_env }}
        run: tox --skip-pkg-install -e ${{ matrix.tox_env }}

  check:
    name: check ${{ matrix.tox_env }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        tox_env:
          - lint
          - docs
    steps:
      - uses: actions/checkout@v3
      - name: setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install prettier
        run: npm install -g prettier
      - name: install tox
        run: python -m pip install tox
      - name: setup test suite for ${{ matrix.tox_env }}
        run: tox -vv --notest -e ${{ matrix.tox_env }}
      - name: run test suite ${{ matrix.tox_env }}
        run: tox --skip-pkg-install -e ${{ matrix.tox_env }}
